# Generated by Django 3.2.9 on 2022-04-06 16:32

from django.db import migrations, models
import imager.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='image',
            field=models.ImageField(height_field=140, upload_to=imager.models.userPath, width_field=140),
        ),
    ]
