# Generated by Django 3.2.9 on 2022-04-06 16:44

from django.db import migrations
import imager.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0003_alter_imager_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=imager.models.userPath),
        ),
    ]
