# Generated by Django 3.2.9 on 2022-04-06 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0005_alter_imager_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imager',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 4, 6)),
        ),
        migrations.AddField(
            model_name='imager',
            name='time',
            field=models.TimeField(auto_created=True, default=datetime.datetime(2022, 4, 6, 23, 53, 55, 622370)),
        ),
    ]
