# Generated by Django 3.2.9 on 2022-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0006_auto_20220406_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='imager',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
    ]
