# Generated by Django 3.2.9 on 2022-04-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0007_auto_20220406_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imager',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
