# Generated by Django 3.2.9 on 2022-04-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0008_auto_20220407_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
